# Generated by Django 3.1.4 on 2021-02-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_auto_20201212_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislike',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
