# Generated by Django 3.1.4 on 2021-02-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_auto_20210214_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
